### ISSUE TITLE
Admin bilgilerinin Session'da tutulmaması lazım

### ISSUE THREAD

**Issue by Orkuncakilkaya** [Ali-Onar/bilgeton#1]
https://github.com/Ali-Onar/bilgeton/blob/fcbd3e1b01cc073e2fd17b230051773bdf307f51/nedmin/sidebar.php#L14

Bu tarz değişebilir dataların session tarafında tutulmaması lazım. Session'da: 
- oturum açmış user'ın idsini
- bir sonraki sayfada tek seferlik gösterilecek mesajların verisini (Flash Alert)
- oturum boyunca tutulacak, kaybı önemsiz kısa süreli verileri

tutabilirsin. Kullanıcının adı soyadı gibi bilgileri, kullanıcın idsini sessiondan alıp mysql'den çektirebilirsin.

**Comment by Ali-Onar** [comment]
Teşekkürler Orkun hocam.
